#Assignment 2

## 1
Convert the above paragraph into vectors using:<br>
i) Word2vec<br>
***ii) USE<br>***
iii)ELMO <br>
iv) GP2<br>
***v) Sentence-BERT***

## Given paragraph as:

In [1]:
my_string='''paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs.  This  is because paragraphs show a reader where the subdivisions of an essay begin 
and end, and thus help the reader see the organization of the essay and grasp its main points.

Paragraphs  can  contain  many  different  kinds  of  information.  A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point.  It  might  describe  a  place like kolkata,  character,  or  process;  narrate  a series of events; compare or contrast two or more things; classify items into 
categories;  or  describe  causes  and  effects.  Regardless  of  the  kind  of information they contain, all paragraphs share certain characteristics. One 
of the most important of these is a topic sentence.'''

print(my_string)

paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs.  This  is because paragraphs show a reader where the subdivisions of an essay begin 
and end, and thus help the reader see the organization of the essay and grasp its main points.

Paragraphs  can  contain  many  different  kinds  of  information.  A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point.  It  might  describe  a  place like kolkata,  character,  or  process;  narrate  a series of events; compare or contrast two or more things; classify items into 
categories;  or  describe  causes  and  effects.  Regardless  of  the  kind  of information they contain, all paragraphs share certain characteristics. One 
of the most important of these is a topic sentence.


In [2]:
import numpy as np
import nltk
import re
import gensim
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from gensim import corpora,models,similarities
from nltk.tokenize import PunktSentenceTokenizer
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

## implementing Word2Vec

In [3]:
#code to convert paragraph to sentences
def essay_to_sentences(paragraph):
    tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
    raw_sentences = tokenizer.tokenize(paragraph.strip())
    s = []
    for raw_sentence in raw_sentences:
        if len(raw_sentence) > 0:
            s.append((raw_sentence))
    return s

s=essay_to_sentences(my_string)

s


['paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.',
 'Almost  every  piece  of  writing  you  do  that  is \nlonger  than  a  few  sentences  should  be  organized  into  paragraphs.',
 'This  is because paragraphs show a reader where the subdivisions of an essay begin \nand end, and thus help the reader see the organization of the essay and grasp its main points.',
 'Paragraphs  can  contain  many  different  kinds  of  information.',
 'A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a \ngeneral  point.',
 'It  might  describe  a  place like kolkata,  character,  or  process;  narrate  a series of events; compare or contrast two or more things; classify items into \ncategories;  or  describe  causes  and  effects.',
 'Regardless  of  the  kind  of information they contain, all paragraphs share certain characteristics.',
 'One \nof the most important of these is a topic s

In [4]:
wordvecs=[nltk.word_tokenize(sent) for sent in s]
from nltk.corpus import stopwords
nltk.download('stopwords')
stops=list(set(stopwords.words("english")))


for i in wordvecs:
  for j in i:
    if j in stops:
      i.remove(j)
    elif len(j)==1:
      i.remove(j)

model=gensim.models.Word2Vec(wordvecs,min_count=1,size=32)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [5]:
  #printing vector form of word 'paragraph'
  model['paragraph']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


array([ 0.00013152,  0.00432548,  0.00590688,  0.01167068,  0.01485313,
        0.00642513,  0.00198989,  0.01051156, -0.01095685,  0.00676491,
       -0.00250168, -0.01351327, -0.00879224, -0.01053118,  0.0030072 ,
        0.00192334, -0.01515282,  0.00928998, -0.01336725,  0.00820398,
        0.00107168, -0.00672934, -0.0035285 ,  0.00362814, -0.01019725,
        0.01169386, -0.00321227,  0.00365423,  0.00967538, -0.00448102,
        0.00079466, -0.01185133], dtype=float32)

In [6]:
#finding similar words of word 'sentence' in given paragraph
model.most_similar('sentence')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('general', 0.25138604640960693),
 ('narrate', 0.24737298488616943),
 ('items', 0.21869313716888428),
 ('piece', 0.20601867139339447),
 ('longer', 0.1984703540802002),
 ('categories', 0.1855049729347229),
 ('characteristics', 0.18319116532802582),
 ('classify', 0.16853122413158417),
 ('series', 0.16658693552017212),
 ('and', 0.15847477316856384)]

## implementing USE

In [7]:
#importing USE model
import tensorflow_hub as hub
use= hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
#converting to vectors
embeddings=use(s)
print(embeddings)

tf.Tensor(
[[ 0.0130397  -0.02448178  0.05377616 ... -0.08659647  0.01437556
   0.04036802]
 [ 0.02902018 -0.00415597  0.07664446 ... -0.06830524 -0.00835191
   0.04397805]
 [ 0.07023076 -0.02952436  0.04878015 ... -0.06741599  0.02838855
   0.06126793]
 ...
 [ 0.04487116 -0.0484449   0.05696819 ... -0.06665879  0.03268223
   0.03346183]
 [ 0.04141247  0.0258891  -0.00625629 ... -0.0216299   0.00910816
   0.03623573]
 [ 0.00255486 -0.05832284  0.01486255 ... -0.09906971 -0.07840379
   0.06731212]], shape=(8, 512), dtype=float32)


In [9]:
print("shape= ",embeddings[1].shape)
#each sentence is converted into vector having 512 values
print("The sentence: ",s[1],"\n is converted as : \n{}".format(embeddings[1]))

shape=  (512,)
The sentence:  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs. 
 is converted as : 
[ 0.02902018 -0.00415597  0.07664446  0.00038611  0.02727121  0.0487924
  0.07609347  0.08293355 -0.00512478  0.06099951 -0.01349433 -0.04980411
 -0.06541967  0.06256042 -0.01149333 -0.09377565  0.01856967 -0.01838753
 -0.01641954 -0.03335263 -0.01566844  0.05477879 -0.05657203 -0.00018438
 -0.04241991  0.00273873  0.03074576 -0.055604   -0.07229963  0.00455274
 -0.0269272  -0.01482788  0.03314197  0.01606584 -0.03317051 -0.02762417
  0.07347243  0.05297884  0.03774318 -0.00830638 -0.00297176  0.01082995
  0.05205777  0.05931166  0.03114958  0.02919524 -0.05279479 -0.06442471
 -0.00450312 -0.02632451  0.01254444 -0.06218815  0.04917336 -0.04414262
 -0.07066017 -0.01131517 -0.03223522  0.01844669  0.03029098  0.02086739
 -0.06771484 -0.0135975   0.07985182  0.02778279  0.05326501  0.03679984
 -0.05332177 -0.057

## SENTENCE BERT

In [10]:
#importing sentencebert model
bert = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
embeddings2=bert(s)
print(embeddings2)

tf.Tensor(
[[ 0.5779494   0.02082791  0.09225276 ...  0.1423439   0.0289949
  -0.15707761]
 [ 0.5166956   0.00863559  0.13047293 ...  0.06873029  0.04432377
   0.02298209]
 [ 0.7741569   0.20155099 -0.06426485 ... -0.15599789  0.10988081
   0.10273374]
 ...
 [ 0.49916965 -0.00334622  0.08184471 ...  0.05571959 -0.09832127
  -0.04315813]
 [ 0.2909918   0.06627773  0.08403497 ... -0.10017543 -0.11646989
   0.00867226]
 [ 0.3799187  -0.05745781  0.09742597 ...  0.0461409  -0.07855327
   0.03973798]], shape=(8, 128), dtype=float32)


In [11]:
print("shape=",embeddings2[1].shape)
#each sentence is converted into vector having 128 values
print("The sentence: ",s[1],"\n is converted as : \n{}".format(embeddings2[1]))

shape= (128,)
The sentence:  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs. 
 is converted as : 
[ 5.16695619e-01  8.63558985e-03  1.30472928e-01  1.15020484e-01
  7.93361664e-02 -8.66438448e-02 -9.05495062e-02 -6.50164858e-02
 -2.20128000e-01  8.06275532e-02 -2.89422423e-02 -1.19031087e-01
 -1.83882877e-01 -1.94603130e-02 -6.80947304e-02  6.74510524e-02
 -4.82805446e-02  9.55083128e-03 -7.67932013e-02  2.41604403e-01
 -1.99953597e-02 -1.42139997e-02  2.60494335e-06 -1.17423102e-01
  5.63744381e-02 -9.02698562e-02  3.30492221e-02 -1.16051055e-01
 -5.65725900e-02 -6.88517839e-02 -1.14481732e-01 -1.52945174e-02
  5.84415533e-02 -3.38245109e-02  9.59906802e-02 -5.53777767e-03
 -5.78031652e-02 -1.00755729e-01  3.73280346e-02  7.17555210e-02
  2.10912134e-02 -4.03055772e-02  5.87721355e-02 -7.50493631e-02
  1.15683302e-01  7.79296607e-02  5.23006916e-02 -1.70393899e-01
 -9.81963351e-02 -6.95727393e-02  3.854040

##implementing ELMOS

In [12]:
!pip install "tensorflow>=2.0.0"
!pip install --upgrade tensorflow-hub

In [13]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#1024 sized vectors
elmo=hub.Module("https://tfhub.dev/google/elmo/3",trainable=True)
embeddings=elmo(
    s,
    signature="default",
    as_dict=True)["elmo"]
init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
print("\n\n")
print(sess.run(embeddings[1]))
print("shape=",embeddings[1].shape)

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


Instructions for updating:
Use `tf.global_variables_initializer` instead.


Instructions for updating:
Use `tf.global_variables_initializer` instead.





[[ 0.3972121  -0.15091433  0.5870079  ... -0.38442358 -0.37334442
   0.13474917]
 [ 0.2227458  -0.12839283  0.01303119 ... -0.29775774 -0.35163897
  -0.05761774]
 [-0.6277796  -0.4548951   0.9650204  ... -0.45376417  0.4266832
   0.10222106]
 ...
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]]
shape= (32, 1024)


## GPT2 

In [14]:
!pip install transformers

     |████████████████████████████████| 3.1 MB 28.6 MB/s 
     |████████████████████████████████| 3.3 MB 40.6 MB/s 
     |████████████████████████████████| 59 kB 6.1 MB/s 
     |████████████████████████████████| 895 kB 33.1 MB/s 
     |████████████████████████████████| 596 kB 42.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [15]:
import torch
import transformers

In [16]:
gptokenizer=transformers.GPT2Tokenizer.from_pretrained('gpt2-large')
model=transformers.GPT2LMHeadModel.from_pretrained('gpt2-large')
output=gptokenizer.encode(my_string,add_special_tokens=False,return_tensors="pt")

Downloading:   0%|          | 0.00/0.99M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.29M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/666 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.02G [00:00<?, ?B/s]

In [ ]:
print("shape=",output.shape)
output

shape= torch.Size([1, 256])


tensor([[20360,   318,   257,  2168,   286, 13439,   326,   389,  8389,   290,
         24870,    11,   290,   389,   477,   220,  3519,   220,   284,   220,
           257,   220,  2060,   220,  7243,    13,   220, 16699,   220,   790,
           220,  3704,   220,   286,   220,  3597,   220,   345,   220,   466,
           220,   326,   220,   318,   220,   198,  6511,   263,   220,   621,
           220,   257,   220,  1178,   220, 13439,   220,   815,   220,   307,
           220,  8389,   220,   656,   220, 23549,    13,   220,   770,   220,
           318,   780, 23549,   905,   257,  9173,   810,   262, 45944,  3279,
           286,   281, 14268,  2221,   220,   198,   392,   886,    11,   290,
          4145,  1037,   262,  9173,   766,   262,  4009,   286,   262, 14268,
           290, 13180,   663,  1388,  2173,    13,   198,   198, 10044,  6111,
            82,   220,   460,   220,  3994,   220,   867,   220,  1180,   220,
          6982,   220,   286,   220,  1321,    13,  



---



---



## 2
 Find named entities (NER) for the above paragraph?

In [18]:

import spacy
from spacy import displacy
ner=spacy.load('en')
result=ner(my_string)

for word in result.ents:
  print(word.text,word.label_)

kolkata PERSON
two CARDINAL
One CARDINAL


In [19]:
spacy.explain('GPE')

'Countries, cities, states'

In [20]:
#better visualisation of entity recognition
displacy.render(result,style="ent",jupyter=True)

In [21]:
# finding named entities of another paragraph
resultss=ner("Bhimrao Ambedkar took birth in a Dalit family on 14th April 1891 to Ramji Maloji Sakpal and Bhimabai. He was from a small Mhow village in Madhya Pradesh. He was a sincere student during his school days. ... Bhimrao Ramji Ambedkar is fondly remembered as Babasaheb because he worked for the Untouchables or Dalits' welfare")
for word in resultss.ents:
  print(word.text,word.label_)

Bhimrao Ambedkar PERSON
Dalit PERSON
14th April 1891 DATE
Ramji Maloji Sakpal PERSON
Bhimabai GPE
his school days DATE
Bhimrao ORG
Ramji Ambedkar PERSON
Babasaheb GPE
Untouchables GPE


In [22]:
#better visualisation of entity recognition
displacy.render(resultss,style="ent",jupyter=True)



---



---



## 3
Find similar sentences(repeated sentences) from the above paragraph?

In [23]:
pip install -U sentence-transformers

     |████████████████████████████████| 78 kB 5.9 MB/s 
     |████████████████████████████████| 1.2 MB 46.5 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.1.0-py3-none-any.whl size=121000 sha256=2929715e6adb8a1d202a4c0bc7263ef68a779fb422d13a2bbedf79267beeb9f9
  Stored in directory: /root/.cache/pip/wheels/90/f0/bb/ed1add84da70092ea526466eadc2bfb197c4bcb8d4fa5f7bad
Successfully built sentence-transformers


In [24]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [27]:
se_embeddings = sbert_model.encode(s)
q1_vec= sbert_model.encode(s[0])

#cosine similarity function
#identifies similarity between 2 sentences
def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for sent in s:
  sim = cosine(q1_vec, sbert_model.encode([sent])[0])
  #if similarity ==1 => repeated sentence
  #if similarity > 0.6 => similar sentence
  if sim>0.6:
    print("Sentence1 =",s[0],"\n \nSentence2=", sent, "\n\nsimilarity = ", sim,end="\n ----------------------------- \n")


Sentence1 = paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 
Sentence2= paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 

similarity =  1.0
 ----------------------------- 
Sentence1 = paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 
Sentence2= Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs. 

similarity =  0.64265954
 ----------------------------- 
Sentence1 = paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 
Sentence2= A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point. 

similarity =  0.6779764
 ----------------------------- 
Sentence1 = paragraph is a series of sentences that are or



---



---

